version: '3'
services:
  database:
    restart: always
    build:
      context: ./mariadb
    container_name: my-web-container
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./mariadb/data.sql:/docker-entrypoint-initdb.d/data.sql
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./src:/var/www
  nginx:
    ports:
      - "80:80"
      - "443:443"
    build:
      context: ./nginx
    volumes:
      - ./src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
